| --------------------------------------------------------------------|
| -- Contains include files for e3x and the specific class
| -- Written and modified by Smaht
| --------------------------------------------------------------------|

| --------------------------------------------------------------------|
| -- Contains includes of the original e3							 -|
| -- Fritten by Killians of PEQ									 	 -|

#include e3 Includes\e3_Background.inc
#include e3 Includes\e3_Buy.inc
#include e3 Includes\e3_Combine.inc
#include e3 Includes\e3_CorpseSummoning.inc
#include e3 Includes\e3_Sell.inc
#include e3 Includes\e3_SmoothMoves.inc

#include e3 Includes\e3_Classes_Berserker.inc

| -- End original e3 includes
| --------------------------------------------------------------------|

| --------------------------------------------------------------------|
| -- Contains includes for e3x (extended)							 -|
| -- Functions written by Smaht									 	 -|

#include e3 Includes\e3x_Alerts.inc
#include e3 Includes\e3x_Assists.inc
#include e3 Includes\e3x_Basics.inc
#include e3 Includes\e3x_BegForBuffs.inc
#include e3 Includes\e3x_BuffCheck.inc
#include e3 Includes\e3x_Casting.inc
#include e3 Includes\e3x_Loot.inc
#include e3 Includes\e3x_ExtraUtilities.inc
#include e3 Includes\e3x_Utilities.inc
#include e3 Includes\e3x_Wait4Rez.inc
#include e3 Includes\e3x_VetAAs.inc

| -- End e3x includes												 -|
| --------------------------------------------------------------------|